---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod-details
  namespace: detail
spec:
  acme:
    email: harsola.gaurav1002@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-details
    solvers:
    - http01:
        ingress:
          class: nginx
