---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alert
spec:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
