global:
  resolve_timeout: 5m
route:
  group_by:
    - cluster
    - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  routes:
    - receiver: slack-notifications
      match:
        severity: warning
    - receiver: pager-duty
      match:
        severity: critical
receivers:
  - name: slack-notifications
    slack_configs:
      - channel: "<channel-name>"
        send_resolved: true
        api_url: "<api-url>"
        title: "{{ .GroupLabels.alertname }}"
        text: "{{ range .Alerts }}{{ .Annotations.message }}\n{{ end }}"
  - name: pager-duty
    pagerduty_configs:
      - routing_key: "$PAGERDUTY_TOKEN"
        severity: "{{ .CommonLabels.severity }}"
        description: '{{ template "pagerduty.default.description" .}}'