
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
  labels:
    team: devops
spec:
  endpoints:
  - interval: 15s
    port: web
    scrapeTimeout: 15s
  selector:
    matchLabels:
      operated-alertmanager: "true"
