kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  namespace: app
  labels:
    app: apple
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=apple"

---

kind: Service
apiVersion: v1
metadata:
  name: apple-service
  namespace: app
spec:
  selector:
    app: apple
  ports:
    - port: 5678 # Default port for image

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: app
  name: apple-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - apple.techdevops.ml
    secretName: apple-devops-com-tls
  rules:
  - host: apple.techdevops.ml        
    http:
      paths:
        - path: /apple
          backend:
            serviceName: apple-service
            servicePort: 5678